//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIForLoginAndReg.Models.AuthModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerRegistration
    {
        public int HotelRegistrationNumber { get; set; }
        public string OwnerName { get; set; }
        public string ContactNumber { get; set; }
        public string HotelName { get; set; }
        public string HotelCity { get; set; }
        public string HotelAddress { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public bool VerifiedStatus { get; set; }
    }
}
